name: Build and deploy a container image to Azure Web Apps

on:
  push:
    branches: [ "Development" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main

    - name: Log in with Azure
      uses: azure/actions/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/container-actions/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push the image tagged with the git commit hash
      run: |
        docker build . -t contoso/demo:${{ github.sha }}
        docker push contoso/demo:${{ github.sha }}

    - name: Update image tag on the Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'Bill-BGD-slots'
        slot-name: 'bill-bgd-slots-Bill-BGD-DEV'
        images: 'contoso/demo:${{ github.sha }}'
